# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160219_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayworking',
            name='hour_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_19',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_20',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_21',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidayworking',
            name='hour_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_19',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_20',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_21',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workingday',
            name='hour_9',
            field=models.BooleanField(default=False),
        ),
    ]
